apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core-services

resources:
  - "mesh/namespace.yaml"
  - "mesh/destination-rule.yaml"
  - "mesh/gateway.yaml"
  - "mesh/items-svc.yaml"
  - "mesh/items-vs.yaml"
  - "mesh/service-entry.yaml"
  - "scopes/items-deployment-beta.yaml"
  - "scopes/items-deployment-omega.yaml"
  - "scopes/items-deployment-prod.yaml"