apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-prod
  labels:
    app: items
    scope: prod
    version: v8
spec:
  selector:
    matchLabels:
      app: items
      scope: prod
  template:
    metadata:
      labels:
        app: items
        scope: prod
        version: v8
    spec:
      containers:
      - name: items
        image: clazz/items-svc:8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
