apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-beta
  labels:
    app: items
    scope: beta
    version: v13
spec:
  selector:
    matchLabels:
      app: items
      scope: beta
  template:
    metadata:
      labels:
        app: items
        scope: beta
        version: v13
    spec:
      containers:
      - name: items
        image: clazz/items-svc:15
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
