apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-omega
  labels:
    app: items
    scope: omega
    version: v9
spec:
  selector:
    matchLabels:
      app: items
      scope: omega
  template:
    metadata:
      labels:
        app: items
        scope: omega
        version: v9
    spec:
      containers:
      - name: items
        image: clazz/items-svc:9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
